apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatgpt-pod
  template:
    metadata:
      labels:
        app: chatgpt-pod
    spec:
      containers:
      - name: mychatgptcontainer
        image: sreekanthargp/chatgpt-project1:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: mysvc-v2
spec:
  type: NodePort
  selector:
    app: chatgpt-pod
  ports:
  - port: 5000 # Service IP Port
    targetPort: 8000 # Container Port
    nodePort: 30002 # Node Port/Host Port
    protocol: TCP
